# Generated by Django 4.2 on 2024-06-22 20:32

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile_pic', models.ImageField(blank=True, null=True, upload_to=accounts.models.MainCustomUser.user_profile_photo)),
                ('contact', models.IntegerField(default=0, verbose_name='Contact')),
                ('website', models.CharField(default='teamstellar.com', max_length=20, verbose_name='Website')),
                ('location', models.CharField(default='karachi', max_length=70, verbose_name='Location')),
                ('doi', models.DateField(blank=True, default='2022-01-01', verbose_name='Date of Incorporation')),
                ('os_name', models.CharField(default='', max_length=100, verbose_name='OS Name')),
                ('system_start_time', models.CharField(default='', max_length=100)),
                ('token', models.CharField(default='', max_length=100)),
                ('type_of_work', models.CharField(default='Social Service', max_length=50, verbose_name='Type of work')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
