# Generated by Django 4.2.4 on 2023-11-19 20:31

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainuser",
            name="contact",
            field=models.IntegerField(default=12345678, verbose_name="Contact"),
        ),
        migrations.AddField(
            model_name="mainuser",
            name="doi",
            field=models.DateField(
                blank=True, default="2022-01-01", verbose_name="Date of Incorporation"
            ),
        ),
        migrations.AddField(
            model_name="mainuser",
            name="location",
            field=models.CharField(
                default="karachi", max_length=70, verbose_name="Location"
            ),
        ),
        migrations.AddField(
            model_name="mainuser",
            name="type_of_work",
            field=models.CharField(
                default="Social Service", max_length=50, verbose_name="Type of work"
            ),
        ),
        migrations.AddField(
            model_name="mainuser",
            name="user_profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.MainUser.user_profile_photo,
            ),
        ),
        migrations.AddField(
            model_name="mainuser",
            name="website",
            field=models.CharField(
                default="teamstellar.com", max_length=20, verbose_name="Website"
            ),
        ),
    ]
