# Generated by Django 4.2 on 2024-06-22 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('tag', models.CharField(max_length=120)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('last_thumpnail', models.ImageField(upload_to='static/media/thumbnails/')),
                ('status', models.BooleanField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='RecordedVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='static/media/videos/')),
                ('status', models.BooleanField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_code', models.CharField(max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('video_url', models.CharField(default='', max_length=255)),
                ('thumb_url', models.CharField(default='', max_length=100)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('live_status', models.IntegerField(default=0)),
                ('image_thumpnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.monitorthumbnail')),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.recordedvideos')),
            ],
        ),
    ]
