# Generated by Django 4.2.4 on 2023-09-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermonitor",
            old_name="username",
            new_name="user_name",
        ),
        migrations.AlterField(
            model_name="usermonitor",
            name="ip_address",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
