# Generated by Django 4.2.4 on 2024-05-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0002_rename_username_usermonitor_user_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermonitor",
            name="video_url",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="usermonitor",
            name="date_create",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="usermonitor",
            name="os",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
