# Generated by Django 4.2.4 on 2024-05-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_api",
            "0003_usermonitor_video_url_alter_usermonitor_date_create_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usermonitor",
            name="thumb_url",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="usermonitor",
            name="user_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="usermonitor",
            name="video_url",
            field=models.CharField(default="", max_length=100),
        ),
    ]
