# Generated by Django 4.2.4 on 2024-05-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0004_usermonitor_thumb_url_alter_usermonitor_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermonitor",
            name="user_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
