# Generated by Django 4.2.4 on 2024-05-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0005_alter_usermonitor_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermonitor",
            name="video_url",
            field=models.CharField(default="", max_length=255),
        ),
    ]
