# Generated by Django 4.2 on 2024-06-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_alter_usermonitor_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermonitor',
            name='live_status',
            field=models.IntegerField(default=0),
        ),
    ]
